### ISSUE TITLE
add native support for adjusting *volume* controls (similar to light levels)

### ISSUE THREAD

**Issue by sumnerboy12** [unityfire/alexa-ha#14]
`ask openhab to turn down the volume in the living room by 10 percent`

**Comment by arch1v1st** [comment]
Hi,

I've been thinking a lot about how to approach media controls.  In addition I intend to add play/pause/next/previous/stop/etc, so users can control media all throughout the house (thinking AVRs and KODI to start).  This will require developing a set of new intents to handle it.

In the mean time you can likely control volume with some config.js changes.  Try using the 'SetLevel' intent.  Create a new config.item like so:

```
    'volume': {
        'living room': 'Living_Volume',
        'office': 'Office_Volume',
        default: 'Office_Volume'
    },
```

And extend the utterances:

```
    'SetLevel': [
        "{to |} {dim|turn down|turn up|soften|adjust} {the|my |} {light|lights|lighting|ItemName} {in the |} {-|Location} to {0-100 by 5|Percent} {percent |}",
        "{to |} {dim|turn down|turn up|soften|adjust} {the|my |} {-|Location} {light|lights|lighting|ItemName} to {0-100 by 5|Percent} {percent |}"
        "{to |} {turn down|turn up|adjust} {the|my |} {-|Location} {volume|audio|sound|ItemName} to {0-100 by 5|Percent} {percent |}"
    ],
```

Then update the list of utterances for your ASK (AWS developer console) and you should be good!

**Comment by sumnerboy12** [comment]
Is this correct `to {0-100 by 5|Percent}`? Should this not be `{to 0-100|by 0-10|Percent}`? Meaning match to either `turn down kitchen volume to 75 percent` or `turn down kitchen volume by 10 percent`?

**Comment by arch1v1st** [comment]
The logic for reducing/increasing by a certain percent isn't there just yet.  So using this existing SetLevel intent, you would set the target volume directly rather than increase/decrease.  Another thought, you would probably want 'set' as part of the utterance, so I'd start with this:

```
"{to |} {set|turn down|turn up|adjust} {the|my |} {-|Location} {volume|audio|sound|ItemName} to {0-100 by 5|Percent} {percent |}"
```

Then you should be able to say:

`Alexa, tell openhab to set the volume in the living room to 60 percent`

**Comment by arch1v1st** [comment]
Careful with this - you don't want to blow your speakers (i.e. 100%).  Hope your target device has some sort of max gain already configured!  ;-)

**Comment by arch1v1st** [comment]
@sumnerboy12 - did my proposed approach work for you?  

If so, I will add this as a stub config option and close this ticket...

**Comment by sumnerboy12** [comment]
I haven't had a chance to with Alexa-HA again sorry. I am wondering if I need a more customised approach, based on your excellent work, for specific questions/instructions, along with a Hue emulator for simple on/off tasks - to save the `ask openhab` bit.

**Comment by arch1v1st** [comment]
Understood; no worries...

We have a few users that are doing just that - using Alexa HA along side a Hue emulator.  That way you have the quickness of the emulator along with the flexibility/feedback that the skill provides.  This definitely improves the WAF :)

Thanks for the kind words!

**Comment by arch1v1st** [comment]
Volume support added to master branch!
https://github.com/unityfire/alexa-ha/pull/19
