### ISSUE TITLE
add support for setting thermostats using celcius

### ISSUE THREAD

**Issue by sumnerboy12** [unityfire/alexa-ha#15]

**Comment by arch1v1st** [comment]
The internationalization of Alexa-HA definitely needs improved. 

To support Celsius with the current version, you could make a few code changes:

-config.js:

```
config.unit = {
    'temperature': 'celsius',
};
```

And in index.js, adjust the SetTemp intent.  These two lines would need amended to some 'sane' checks for Celsius values:

```
if (degree && degree > 60 && degree < 80 && HA_item) {

replyWith('I could not set your ' + location + ' to ' + degree + ' degrees.  Try something between 60 and 80 degrees fahrenheit.', response);
```

**Comment by arch1v1st** [comment]
As mentioned in the new [Amazon Smart Home API](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference) documentation, Celsius should be the default unit.  In addition this approach is common across various smart thermostat manufacturers.  In the next release, Alexa HA will default to Celsius and provide an easy way to switch units via a configuration option; everything else (utterances, cards, etc) will be handled automatically.

**Comment by sumnerboy12** [comment]
sounds good

**Comment by arch1v1st** [comment]
Closing this issue and deprecating this project in favor of the new OpenHAB v3 Alexa binding!
