### ISSUE TITLE
Getting privateKey or certificate do not exist in /sslcert

### ISSUE THREAD

**Issue by tstasevych** [unityfire/alexa-ha#28]
I followed your instructions using Ubuntu 14.04. Getting this error:

```
alexa@alexa-ha:~/node_modules/alexa-app-server/api$ node server.js
Serving static content from: public_html
Loading server-side modules from: server
   Loaded /home/alexa/node_modules/alexa-app-server/api/server/login.js
Loading apps from: apps
   Loaded app [Alexa-HA] at endpoint: /api/Alexa-HA
httpsEnabled is true. Reading HTTPS config
privateKey: 'private-key.pem' or certificate: 'cert.cer' do not exist in /sslcert. HTTPS will not be enabled
Listening on HTTP port 30000
```

server.js file:

```
var AlexaAppServer = require("../index.js");
AlexaAppServer.start( {
        app_dir:"apps",
        app_root:"/api/",
        port:30000,
        httpsEnabled:true,
        httpsPort:30001,
        privateKey:'private-key.pem',
        certificate:'cert.cer'

        // Use preRequest to load user data on each request and add it to the request json.
        // In reality, this data would come from a db or files, etc.
        ,preRequest: function(json,req,res) {
                //console.log("preRequest fired");
                //json.userDetails = { "name":"Bob Smith" };
                json.password = req.param('xxxxxxxxx').toString();
                var IPFromRequest = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
                var indexOfColon = IPFromRequest.lastIndexOf(':');
                var address = IPFromRequest.substring(indexOfColon+1,IPFromRequest.length);
                json.remoteAddress = address;
        }
        // Add a dummy attribute to the response
        ,postRequest: function(json,req,res) {
                //json.dummy = "text";
        }
} );
```

But as you see below, files exist:

```
alexa@alexa-ha:~/node_modules/alexa-app-server/api$ ls /home/alexa/node_modules/alexa-app-server/api/apps/alexa-ha/sslcert/
cert.cer  private-key.pem
```

Thanks!

**Comment by arch1v1st** [comment]
Based on your description, I am guessing that you are facing a a permissions issue.  Double check that the user invoking node (i.e. 'alexa') can read these files.  In my case they are all owned by the 'alexa' user, but you could consider 'chmod 755' for testing purposes too!

**Comment by tstasevych** [comment]
Thank you so much for quick response. 
I have created files using alexa account. ls -l shows alexa is owner. 
I tried chmod 755, it did not make a difference. Any help much appreciated.

BR,
Ted

![image](https://cloud.githubusercontent.com/assets/17030557/18939929/deb8bc4c-85c9-11e6-9cf9-f615e43f7291.png)

**Comment by tstasevych** [comment]
![image](https://cloud.githubusercontent.com/assets/17030557/18940194/97e08dd4-85cb-11e6-8e15-cd71374c76af.png)

**Comment by 2MuchTech** [comment]
Are you sure it's not looking for the certs in a directory called sslcert off the root directory?  The error message says it can't find them in /sslcert (not ./sslcert), which taken literally would mean off the root directory.  If that's not it, have you checked the permissions of the sslcert directory?

**Comment by arch1v1st** [comment]
Thanks a lot for assisting @2MuchTech!  To test your theory out I logged into my working server, moved cert.cer elsewhere, and restarted.  The error @tstasevych had matched what I experienced, so its not a relative path problem.

@tstasevych - your path is incorrect as you have /sslcert in ~/node_modules/alexa-app-server/api/apps/alexa-ha, but it should be under ~/node_modules/alexa-app-server/api.  Run this and you should be in business!

```
cd ~/node_modules/alexa-app-server/api/apps/alexa-ha
mv sslcert ../../
```

Noted the instructions are not clear on this location, I will update them as needed soon.

**Comment by tstasevych** [comment]
That was it! Thank you so much for help. Will continue setup.
