### ISSUE TITLE
Call to action - code overhaul

### ISSUE THREAD

**Issue by arch1v1st** [unityfire/alexa-ha#31]
Support for both OpenHAB v1/v2 requires a major overhaul of the OH APIs, and should eliminate the use of LITERAL slot types before Amazon removes them on February 06 2017.

Please comment if you are willing and able to assist with development & testing the next iteration of Alexa-HA!

**Comment by peacepenguin** [comment]
I would love to test! I want to move to openhab 2 but Alexa-HA is keeping me back as it is working great for me on OH1.8.3. I might be able to help with dev, but I mostly write scripts (powershell, bash) Let me know and I'll assist anywhere I can. 

I'm good at creating vm appliances and automation, maybe I could help with continuous integration testing and automatic build up of a live environment with Openhab and Alexa-ha ready to test. This app in particular requires some leg work to initially setup as it requires a full openhab setup, so anything  to remove barriers to getting more people looking at the app is good.

Glad to see you advancing Alexa-HA into its 2nd generation!

**Comment by tiny-tinker** [comment]
I am interested in either dev or testing, but I won't have too many cycles until late January.

**Comment by arch1v1st** [comment]
Thank you both!

@peacepenguin - I'm honored that Alexa-HA has been seemingly instrumental with your Home Automation there, and you've stuck with OpenHAB v1.x specifically because of Alexa-HA.  Stoked to get OpenHAB v2.x support working for you and the OpenHAB community at large, ASAP!

@nomadic-squirrel - understood; I will be sure to keep you looped in as things transpire.

**Comment by kaikreuzer** [comment]
@arch1v1st Shame on my, I only learned about your awesome project today!
You might have seen that we [launched the new myopenHAB](https://community.openhab.org/t/myopenhab-replaces-my-openhab/18258) yesterday, which (soon) comes with an Alexa Smart Home skill. I would love to also add a custom skill, which would add a lot more possibilities as your project shows.
As self-hosting a skill is only interesting for a small number of users, I think it would be great if we would find a way to host this on myopenHAB for everyone - and I'd love to help getting this to openHAB 2, because this is where we have the chance to enhance the runtime APIs and which will become the mainstream release early next year anyhow.
Sorry, if I highjacked this thread here, didn't mean to. Feel free to PM my on [the forum](https://community.openhab.org) to further discuss!

**Comment by peacepenguin** [comment]
@arch1v1st  Do you have a donation page or paypal? Your app is instrumental to me and I'd love to donate to help encourage your continued dev and support of your Alexa-HA code. It really ties the room together!

**Comment by arch1v1st** [comment]
@peacepenguin - thanks for the thought & offer, you rock!!!

My personal paypal link is:
paypal.me/arch1v1st

FYI - Any and all donations are sincerely appreciated!

**Comment by arch1v1st** [comment]
Donation received!  What goes around, comes around!  Thnx ;)

**Comment by seaside1** [comment]
I can help to test things out if needed.

**Comment by digiltd** [comment]
I am a web dev, frontend (html/css/scss/javascript build tools etc) and backend (php/a dash of node/Python/AWS/networking/hosting(apache/nginx/vps)/security etc)

I also dabble with developing my own Skills and have occasionally contributed to the kodi-alexa Skill. 

Happy to help

**Comment by phprehl** [comment]
I can help testing if needed

**Comment by arch1v1st** [comment]
@seaside1 & @digiltd & @phprehl - thank you all for the support.  Major updates to Alexa-HA are coming!  I will keep you all apprised.

-M

**Comment by paphko** [comment]
I observed that this skill and the official openhab-alexa skill both implement a rest client for openhab ([openhab.js](https://github.com/unityfire/alexa-ha/blob/master/lib/openhab.js) vs. [rest.js](https://github.com/openhab/openhab-alexa/blob/master/rest.js)). What about merging the code for the custom skill will the code from the smarthome skill? A single lambda function could be used for both triggers (smarthome and custom skill) and then delegate to the two different handlers. Then we can eliminate code with the same logic and re-use existing functionality.

I am currently trying to create a single lambda function which serves both skills. I'll post again as soon as I got it working.

Update: It's working, I can now use the same lambda function for a smarthome and a custom skill to control openhab. Next, I'll try to merge the rest clients into a single file.

**Comment by arch1v1st** [comment]
Awesome! Kindly submit a PR or create a new branch! :)

**Comment by paphko** [comment]
First of all, I would like to enable yet another way of specifying smarthome items for Alexa skills, namely via groups: https://github.com/openhab/openhab-alexa/issues/4 - this enables alexa support also for OH1 and adds an alternative way of configuring OH2 items for Alexa. After this is done, we should unify code for connecting to openhab via REST ([openhab.js](https://github.com/unityfire/alexa-ha/blob/master/lib/openhab.js) vs. [rest.js](https://github.com/openhab/openhab-alexa/blob/master/rest.js), [oh1.js](https://github.com/openhab/openhab-alexa/blob/master/oh1.js), and [oh2.js](https://github.com/openhab/openhab-alexa/blob/master/oh2.js))?

I don't know if there is a more elegant way of merging code from [openhab/openhab-alexa](https://github.com/openhab/openhab-alexa) and [unityfire/alexa-ha](https://github.com/unityfire/alexa-ha) other than copying the sources of one repo into the other?

I would also suggest to remove the wolfram alpha integration. This should rather be a dedicated skill IMHO?!

**Comment by paphko** [comment]
FYI, I forked openhab-alexa [here](https://github.com/paphko/openhab-alexa/tree/oh1_oh2_groups) which now supports OH1 and OH2. Redundant code is removed. Now, an item group can also be used (in [config file](https://github.com/paphko/openhab-alexa/blob/oh1_oh2_groups/config_sample.js)) to specify which items should be discoverable by Alexa.

**Comment by paphko** [comment]
FYI, I just stumbled over [this blog post](https://developer.amazon.com/blogs/post/Tx3IHSFQSUF3RQP/why-a-custom-slot-is-the-literal-solution) which explains how to properly replace the LITERAL slot type.

**Comment by arch1v1st** [comment]
@paphko - THANKS for sharing all of this.  

"this enables alexa support also for OH1 and adds an alternative way of configuring OH2 items for Alexa. After this is done, we should unify code for connecting to openhab via REST (openhab.js vs. rest.js, oh1.js, and oh2.js)?"

I agree with your comment that OH1 will be superseded by OH2 soon enough, maybe more effort than its worth...  Though I do like thought of having support for all OH users regardless of which version they are using :)

"FYI, I forked openhab-alexa here which now supports OH1 and OH2. Redundant code is removed. Now, an item group can also be used (in config file) to specify which items should be discoverable by Alexa."

Very cool!  Looking forward to experimenting with this hands on!

"FYI, I just stumbled over this blog post which explains how to properly replace the LITERAL slot type."

Excellent - exactly what I was looking for.  Seems CUSTOM slot types need to be wired in to replace LITERAL slot types throughout Alexa-HA's code base.  On my list of todo items!

**Comment by MrMontesa** [comment]
Since OH2 went into prod yesterday I would not focus on OH1 any longer. This great addons should be on the list of reasons to migrate to OH2. 
I guess removing support for OH1 might also remove complexity from the addons. 
Happy to test any new version as alexa is my focus area these days.

**Comment by arch1v1st** [comment]
@MrMontesa 

Points taken; yes I definitely intend to switch gears to focusing on OH2 support with only minor maintanence to the Alexa HA OH1 version.  The blocker for me is spending the time for migrating all of my existing logic/rules to OH2 before Alexa HA rework can begin - but that should go quick!  :)

**Comment by digiltd** [comment]
@arch1v1st I completely agree, I must have attempted setting up OH2 at least 10 times in recent months. Pretty sure and early release of OH2 was available back when I started in July 2015. It took a lot of time and learning to get my OH1 setup to a point where I trust it and rely on it.  Each time I try to understand OH2 and what I need to do to upgrade I always hit a wall and give up. 

I'm sure it will click with me eventually but I don't get how the interface in OH2 seems to be so detached from the text files. The interface seems to be very useful and the biggest change, but if you want to write rules you have to do that in text files. You can't add an item in the UI and have it appear on your items list in a text editor and you can't create dummy switches or variables etc without using a text editor (I think). But we are moving house soon, and I will try to setup the new house from scratch, which should be easier than trying to upgrade my loverly working version :)

**Comment by arch1v1st** [comment]
Closing this issue and deprecating this project in favor of the new OpenHAB v3 Alexa binding!
