### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by phprehl** [unityfire/alexa-ha#32]
I would like to have a multilingual openhab skill.
I would recommend to have a language file for every supported language. In this language all texts can be stored. You can than create a variable in config.js to select the correct language file. This var is then exported as language and can be used in index.js or helper.js.

Any thoughts on this?

**Comment by arch1v1st** [comment]
Agreed!  When Alexa-HA development began, it was only available in the US in English, but I see it's now officially available in the UK and Germany so its safe to assume other languages will be officially supported soon.

I'll wire support for multiple languages as time permits, in addition to support for Celsius units (#15).

Thanks!

**Comment by phprehl** [comment]
I have tried to wire support for multiple languages into the switch intent. I already described the changes some time ago in the openhab community forum. It still a little bit rough in the German version. I hope I did not break the English version.
Are you interested in a pull request?

**Comment by arch1v1st** [comment]
@phprehl - now that you mention it I do recall (quite a while back, sorry this hasn't happened sooner); a PR would be excellent!  I would like extend and merge it into our develop branch to start.

Cheers,
.

**Comment by arch1v1st** [comment]
Thanks a lot!  I will thoroughly review this hands on ASAP.

**Comment by staehler** [comment]
As I'm quiet keen on the german version as well, so I would support by translation, if this helps. Please let me know ...
As I already mentioned in this [post ](https://community.openhab.org/t/amazon-echo-skill-for-openhab-available/8113/236?u=staehler67), in the german language there are some synonyms possible for the Action values. A mapping for some action values to ON or OFF would be nice. Also are Actions needed for the roller shutter like UP and DOWN (in german _auf, rauf, hoch_ for UP and _zu, runter_ for DOWN).
It seems, that LITERAL slots are not supported in german echo skills, they need to be replaced by custom slots, which could reduce the utterances dramatically.

**Comment by staehler** [comment]
Despite of the utterance_literal patch, the intent schema contains LITERALS
`{ "intents": [ { "intent": "Switch", "slots": [ { "name": "Action", "type": "LITERAL" }, { "name": "ItemName", "type": "LITERAL" }, { "name": "Location", "type": "LOCATION_TYPE" } ] },`
What do I wrong?

**Comment by arch1v1st** [comment]
Hi @staehler 

We certainly appreciate the offer and will keep this issue updated as things progress.

Regarding LITERAL slot types - this is was a major change enforced by Amazon recently; I have not had the time to update Alexa HA just yet to switch all LITERAL slots to CUSTOM.  This will certainly be updated to accommodate in due time!

**Comment by arch1v1st** [comment]
Closing this issue and deprecating this project in favor of the new OpenHAB v3 Alexa binding!
