### ISSUE TITLE
A new docker image

### ISSUE THREAD

**Issue by martinvw** [unityfire/alexa-ha#35]
Hello,

When I was setting this up I read some good remarks about shielding this from the rest of your HA system. So the first thing that popped up in my mind was using a docker to do this separation, I created an initial docker which works out great. How do you feel about linking our projects in some way?

https://github.com/martinvw/alexa-ha-docker

Regards,

Martin van Wingerden

**Comment by arcanon** [comment]
As a user, it would be easiest if its just a binding you install. the hue emulator binding is like that. one click and you have it running from the paper UI. I don't know if a binding would be able to install a docker image, but that would be quite cool. that might be overkill if a binding package can some how "be the container" for alexa-ha anyway.

**Comment by martinvw** [comment]
Note that I added [README](https://github.com/martinvw/alexa-ha-docker) now and published it to [docker hub](https://hub.docker.com/r/martinvw/alexa-ha/)

**Comment by arch1v1st** [comment]
Martin - this looks awesome; thanks for contributing.  Your docker image will make it much more straight forward for others to get up and going quickly.  While I agree with @arcanon that a binding would be ideal, the technologies at play and the complexities of dealing with Amazon Alexa Skills Kit make it extremely difficult to repacking Alexa HA (custom skill, not a Smart Home Skill) as a native OpenHAB binding.

More to come!

**Comment by sjp770** [comment]
Hi Martin, any chance you could set this docker up for Unraid? It would increase its exposure as it allows installation with a few clicks. If you haven't seen it it's a Nas type OS that has a Catalog of dockers and even an app store. I have openhab2 and letsencrypt running through it.

**Comment by martinvw** [comment]
@sjp770 could you give me any hints what is required for setting up for unraid? You are welcome to create a pull request if you are able to do it yourselves!

**Comment by sjp770** [comment]
Sorry, no idea on either count but I'll be installing your docker manually
tonight. Thanks for setting it up.
