### ISSUE TITLE
Alexa Utterances patch required for custom slot types

### ISSUE THREAD

**Issue by arch1v1st** [unityfire/alexa-ha#4]
The attached patch is currently needed for Alexa Utterances module to be able to support the new custom slot types.  Hopefully this is merged into master soon!

[alexa-utterances_custom_slot_support.patch.txt](https://github.com/unityfire/alexa-ha/files/155821/alexa-utterances_custom_slot_support.patch.txt)

To install, cd into your node_module alexa-utterances directory, and:

```
wget https://github.com/unityfire/alexa-ha/files/155821/alexa-utterances_custom_slot_support.patch.txt
patch -p1 < alexa-utterances_custom_slot_support.patch.txt
```

**Comment by arch1v1st** [comment]
For reference, I've raised a request for this to be applied upstream:

https://github.com/mreinstein/alexa-utterances/issues/8

**Comment by arch1v1st** [comment]
This hack could possibly replace the need for the alexa-utterances patch:
https://github.com/bignerdranch/alexa-airportinfo/blob/master/index.js#L43

**Comment by mreinstein** [comment]
we've pushed alexa-utterances@0.2.0 which should have this functionality you're looking for. let me know if there's any issues.

**Comment by arch1v1st** [comment]
@mreinstein - thanks a lot; I will test this ASAP!

**Comment by arch1v1st** [comment]
Closing this issue and deprecating this project in favor of the new OpenHAB v3 Alexa binding!
